"""recreate db for postress

Revision ID: c4be15d809a3
Revises: 
Create Date: 2023-09-30 16:44:20.360572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4be15d809a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(length=100), nullable=False),
    sa.Column('search_name', sa.String(length=100), nullable=False),
    sa.Column('oracle_text', sa.String(), nullable=False),
    sa.Column('type_line', sa.String(length=100), nullable=False),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('toughness', sa.Integer(), nullable=True),
    sa.Column('mana_cost', sa.String(length=50), nullable=False),
    sa.Column('cmc', sa.Integer(), nullable=False),
    sa.Column('color_identity', sa.String(length=5), nullable=False),
    sa.Column('card_img', sa.String(), nullable=False),
    sa.Column('double_sided_pointer', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardgram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('n_gram', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commander',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commander_name', sa.String(length=100), nullable=False),
    sa.Column('search_name', sa.String(length=100), nullable=False),
    sa.Column('card_img', sa.String(), nullable=False),
    sa.Column('last_scraped', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_name', sa.String(length=20), nullable=False),
    sa.Column('keyword_definition', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=75), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)

    op.create_table('card_keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardgram_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('cardgram_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['cardgram_id'], ['cardgram.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commander_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commander_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['commander_id'], ['commander.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commander_gram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('n_gram', sa.String(length=100), nullable=False),
    sa.Column('n_count', sa.Integer(), nullable=False),
    sa.Column('commander_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commander_id'], ['commander.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deck_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_commander', sa.Boolean(), nullable=False),
    sa.Column('is_maindeck', sa.Boolean(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deck_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_term', sa.String(length=50), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deck_search')
    op.drop_table('deck_collection')
    op.drop_table('deck')
    op.drop_table('commander_gram')
    op.drop_table('commander_collection')
    op.drop_table('cardgram_collection')
    op.drop_table('card_keyword')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_token'))

    op.drop_table('user')
    op.drop_table('keyword')
    op.drop_table('commander')
    op.drop_table('cardgram')
    op.drop_table('card')
    # ### end Alembic commands ###
